### ISSUE TITLE
Cannot delete a recommendation request after it is completed.

### ISSUE THREAD

**Issue by FrostXTJ** [andyzhou1999/csci-401-capstone#14]
I am running the app locally and I am unable to delete a recommendation request after it is completed, here is the error message printed out on the console:
```
Error: User validation failed: templates.0.questions.7.type: `Text Answer` is not a valid enum value for path `type`.
    at ValidationError.inspect (/Users/tianjianxu/GitRepository/csci-401-capstone/letterOfRecGenerator/node_modules/mongoose/lib/error/validation.js:48:26)
    at formatValue (node:internal/util/inspect:761:19)
    at inspect (node:internal/util/inspect:338:10)
    at formatWithOptionsInternal (node:internal/util/inspect:2004:40)
    at formatWithOptions (node:internal/util/inspect:1886:10)
    at console.value (node:internal/console/constructor:327:14)
    at console.log (node:internal/console/constructor:363:61)
    at /Users/tianjianxu/GitRepository/csci-401-capstone/letterOfRecGenerator/routes/recommender-dashboard.js:117:21
    at /Users/tianjianxu/GitRepository/csci-401-capstone/letterOfRecGenerator/node_modules/mongoose/lib/model.js:5074:18
    at processTicksAndRejections (node:internal/process/task_queues:78:11) {
  errors: {
    'templates.0.questions.7.type': ValidatorError: `Text Answer` is not a valid enum value for path `type`.
        at validate (/Users/tianjianxu/GitRepository/csci-401-capstone/letterOfRecGenerator/node_modules/mongoose/lib/schematype.js:1270:13)
        at /Users/tianjianxu/GitRepository/csci-401-capstone/letterOfRecGenerator/node_modules/mongoose/lib/schematype.js:1253:7
        at Array.forEach (<anonymous>)
        at SchemaString.SchemaType.doValidate (/Users/tianjianxu/GitRepository/csci-401-capstone/letterOfRecGenerator/node_modules/mongoose/lib/schematype.js:1198:14)
        at /Users/tianjianxu/GitRepository/csci-401-capstone/letterOfRecGenerator/node_modules/mongoose/lib/document.js:2567:18
        at processTicksAndRejections (node:internal/process/task_queues:78:11) {
      properties: [Object],
      kind: 'enum',
      path: 'type',
      value: 'Text Answer',
      reason: undefined,
      [Symbol(mongoose:validatorError)]: true
    }
  },
  _message: 'User validation failed'
}
```

**Comment by andyzhou1999** [comment]
I think the issue is with the creation of questions in frontend script. Please do a git pull and see if this issue persist.
