### ISSUE TITLE
Cannot open the form link when the app is running locally

### ISSUE THREAD

**Issue by FrostXTJ** [andyzhou1999/csci-401-capstone#3]
I run the app locally. I received the email after a recommendation request was created. But I cannot open the link in the email to fill out the form.

Create a recommendation request:
![Screen Shot 2021-09-20 at 9 21 07 AM](https://user-images.githubusercontent.com/41350819/134038273-a2c487c6-79ca-4027-8ffd-6249f16c2a8d.png)

After clicking on this link, I cannot proceed:
![image](https://user-images.githubusercontent.com/41350819/134038560-154fb3fd-ce0b-478c-96bc-4d11eefc946b.png)

These warning messages are logged onto the screen, not sure if they are relevant:
```
undefined
ReferenceError: /Users/tianjianxu/GitRepository/csci-401-capstone/letterOfRecGenerator/views/pages/recommender-dashboard.ejs:123
    121|                         <div class="email-input">
    122|                             <p class="hint">Subject </p>
 >> 123|                             <input class="input-text" id="subject" type="text" name="subject_text" value="<%= subject%>" >
    124|                         </div>
    125|                         <textarea id="body-text" name="body_text"><%= body%></textarea>
    126|                     </div>

subject is not defined
    at eval (/Users/tianjianxu/GitRepository/csci-401-capstone/letterOfRecGenerator/views/pages/recommender-dashboard.ejs:42:26)
    at recommender-dashboard (/Users/tianjianxu/GitRepository/csci-401-capstone/letterOfRecGenerator/node_modules/ejs/lib/ejs.js:682:17)
    at tryHandleCache (/Users/tianjianxu/GitRepository/csci-401-capstone/letterOfRecGenerator/node_modules/ejs/lib/ejs.js:254:36)
    at View.exports.renderFile [as engine] (/Users/tianjianxu/GitRepository/csci-401-capstone/letterOfRecGenerator/node_modules/ejs/lib/ejs.js:485:10)
    at View.render (/Users/tianjianxu/GitRepository/csci-401-capstone/letterOfRecGenerator/node_modules/express/lib/view.js:135:8)
    at tryRender (/Users/tianjianxu/GitRepository/csci-401-capstone/letterOfRecGenerator/node_modules/express/lib/application.js:640:10)
    at Function.render (/Users/tianjianxu/GitRepository/csci-401-capstone/letterOfRecGenerator/node_modules/express/lib/application.js:592:3)
    at ServerResponse.render (/Users/tianjianxu/GitRepository/csci-401-capstone/letterOfRecGenerator/node_modules/express/lib/response.js:1012:7)
    at /Users/tianjianxu/GitRepository/csci-401-capstone/letterOfRecGenerator/routes/recommender-dashboard.js:123:25
    at /Users/tianjianxu/GitRepository/csci-401-capstone/letterOfRecGenerator/models/user.js:282:7
    at /Users/tianjianxu/GitRepository/csci-401-capstone/letterOfRecGenerator/node_modules/mongoose/lib/model.js:5074:18
    at processTicksAndRejections (node:internal/process/task_queues:78:11) {
  path: '/Users/tianjianxu/GitRepository/csci-401-capstone/letterOfRecGenerator/views/pages/recommender-dashboard.ejs'
}
POST /recommender-dashboard/delete 500 25.960 ms - 2971
undefined

......

Message sent: <7905ff20-abd4-966e-f884-f6f4895c5f49@gmail.com>
Preview URL: false
Error: Failed to lookup view "contact" in views directory "/Users/tianjianxu/GitRepository/csci-401-capstone/letterOfRecGenerator/views"
    at Function.render (/Users/tianjianxu/GitRepository/csci-401-capstone/letterOfRecGenerator/node_modules/express/lib/application.js:580:17)
    at ServerResponse.render (/Users/tianjianxu/GitRepository/csci-401-capstone/letterOfRecGenerator/node_modules/express/lib/response.js:1012:7)
    at /Users/tianjianxu/GitRepository/csci-401-capstone/letterOfRecGenerator/routes/recommender-dashboard.js:104:21
    at /Users/tianjianxu/GitRepository/csci-401-capstone/letterOfRecGenerator/node_modules/nodemailer/lib/mailer/index.js:226:21
    at /Users/tianjianxu/GitRepository/csci-401-capstone/letterOfRecGenerator/node_modules/nodemailer/lib/smtp-transport/index.js:247:32
    at callback (/Users/tianjianxu/GitRepository/csci-401-capstone/letterOfRecGenerator/node_modules/nodemailer/lib/smtp-connection/index.js:435:13)
    at /Users/tianjianxu/GitRepository/csci-401-capstone/letterOfRecGenerator/node_modules/nodemailer/lib/smtp-connection/index.js:458:24
    at SMTPConnection._actionSMTPStream (/Users/tianjianxu/GitRepository/csci-401-capstone/letterOfRecGenerator/node_modules/nodemailer/lib/smtp-connection/index.js:1481:20)
    at SMTPConnection.<anonymous> (/Users/tianjianxu/GitRepository/csci-401-capstone/letterOfRecGenerator/node_modules/nodemailer/lib/smtp-connection/index.js:968:22)
    at SMTPConnection._processResponse (/Users/tianjianxu/GitRepository/csci-401-capstone/letterOfRecGenerator/node_modules/nodemailer/lib/smtp-connection/index.js:764:20)
    at SMTPConnection._onData (/Users/tianjianxu/GitRepository/csci-401-capstone/letterOfRecGenerator/node_modules/nodemailer/lib/smtp-connection/index.js:570:14)
    at TLSSocket.<anonymous> (/Users/tianjianxu/GitRepository/csci-401-capstone/letterOfRecGenerator/node_modules/nodemailer/lib/smtp-connection/index.js:522:47)
    at TLSSocket.emit (node:events:365:28)
    at addChunk (node:internal/streams/readable:314:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at TLSSocket.Readable.push (node:internal/streams/readable:228:10)
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23) {
  view: View {
    defaultEngine: 'ejs',
    ext: '.ejs',
    name: 'contact',
    root: '/Users/tianjianxu/GitRepository/csci-401-capstone/letterOfRecGenerator/views',
    engine: [Function (anonymous)],
    path: undefined
  }
}
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at new NodeError (node:internal/errors:363:5)
    at ServerResponse.setHeader (node:_http_outgoing:574:11)
    at ServerResponse.header (/Users/tianjianxu/GitRepository/csci-401-capstone/letterOfRecGenerator/node_modules/express/lib/response.js:771:10)
    at ServerResponse.send (/Users/tianjianxu/GitRepository/csci-401-capstone/letterOfRecGenerator/node_modules/express/lib/response.js:170:12)
    at done (/Users/tianjianxu/GitRepository/csci-401-capstone/letterOfRecGenerator/node_modules/express/lib/response.js:1008:10)
    at tryHandleCache (/Users/tianjianxu/GitRepository/csci-401-capstone/letterOfRecGenerator/node_modules/ejs/lib/ejs.js:260:5)
    at View.exports.renderFile [as engine] (/Users/tianjianxu/GitRepository/csci-401-capstone/letterOfRecGenerator/node_modules/ejs/lib/ejs.js:485:10)
    at View.render (/Users/tianjianxu/GitRepository/csci-401-capstone/letterOfRecGenerator/node_modules/express/lib/view.js:135:8)
    at tryRender (/Users/tianjianxu/GitRepository/csci-401-capstone/letterOfRecGenerator/node_modules/express/lib/application.js:640:10)
    at Function.render (/Users/tianjianxu/GitRepository/csci-401-capstone/letterOfRecGenerator/node_modules/express/lib/application.js:592:3)
    at ServerResponse.render (/Users/tianjianxu/GitRepository/csci-401-capstone/letterOfRecGenerator/node_modules/express/lib/response.js:1012:7)
    at /Users/tianjianxu/GitRepository/csci-401-capstone/letterOfRecGenerator/app.js:163:7
    at Layer.handle_error (/Users/tianjianxu/GitRepository/csci-401-capstone/letterOfRecGenerator/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/Users/tianjianxu/GitRepository/csci-401-capstone/letterOfRecGenerator/node_modules/express/lib/router/index.js:315:13)
    at /Users/tianjianxu/GitRepository/csci-401-capstone/letterOfRecGenerator/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/tianjianxu/GitRepository/csci-401-capstone/letterOfRecGenerator/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/tianjianxu/GitRepository/csci-401-capstone/letterOfRecGenerator/node_modules/express/lib/router/index.js:275:10)
    at Layer.handle_error (/Users/tianjianxu/GitRepository/csci-401-capstone/letterOfRecGenerator/node_modules/express/lib/router/layer.js:67:12)
    at trim_prefix (/Users/tianjianxu/GitRepository/csci-401-capstone/letterOfRecGenerator/node_modules/express/lib/router/index.js:315:13)
    at /Users/tianjianxu/GitRepository/csci-401-capstone/letterOfRecGenerator/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/tianjianxu/GitRepository/csci-401-capstone/letterOfRecGenerator/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/tianjianxu/GitRepository/csci-401-capstone/letterOfRecGenerator/node_modules/express/lib/router/index.js:275:10)
    at /Users/tianjianxu/GitRepository/csci-401-capstone/letterOfRecGenerator/node_modules/express/lib/router/index.js:635:15
    at IncomingMessage.next (/Users/tianjianxu/GitRepository/csci-401-capstone/letterOfRecGenerator/node_modules/express/lib/router/index.js:260:14)
    at done (/Users/tianjianxu/GitRepository/csci-401-capstone/letterOfRecGenerator/node_modules/express/lib/response.js:1007:25)
    at Function.render (/Users/tianjianxu/GitRepository/csci-401-capstone/letterOfRecGenerator/node_modules/express/lib/application.js:582:14)
    at ServerResponse.render (/Users/tianjianxu/GitRepository/csci-401-capstone/letterOfRecGenerator/node_modules/express/lib/response.js:1012:7)
    at /Users/tianjianxu/GitRepository/csci-401-capstone/letterOfRecGenerator/routes/recommender-dashboard.js:104:21
```

**Comment by andyzhou1999** [comment]
You will need to remove the 3000 port from the link. The generation process have that bug. I will do a fix and it should work after that

**Comment by andyzhou1999** [comment]
During local dev, it will need to remove the 3000 port. On server, it works fine
